import PrimeNumberTheoremAnd.RiemannVonMangoldtIdentity

#check riemannXi_meromorphicOn
#check riemannXi_logDeriv_meromorphicOn
#check riemannXi_meromorphicOrderAt_ne_top
#check riemannXi_no_boundary_divisor_support
#check riemannXi_rectangleIntegral_logDeriv_eq_sum_meromorphicOrderAt
#check riemannXi_rectangle_argumentChange_eq_two_pi_sum_meromorphicOrderAt

#print axioms riemannXi_rectangleIntegral_logDeriv_eq_sum_meromorphicOrderAt
#print axioms riemannXi_rectangle_argumentChange_eq_two_pi_sum_meromorphicOrderAt
