import PrimeNumberTheoremAnd.Backlund.Eccentric

#check Backlund.eccentricHighRhs
#check Backlund.kadiriRhs
#check Backlund.zeta_one_line_le_const_mul_log
#check Backlund.backlundA
#check Backlund.backlundA_zero_line_le_const_mul_log
#check Backlund.zetaSurrogate_zero_line_le_const_mul_shiftedLog
#check Backlund.zetaSurrogate_one_line_le_const_mul_shiftedLog
#check Backlund.zetaSurrogate_zero_line_le_const_mul_shiftedLog_global
#check Backlund.zetaSurrogate_one_line_le_const_mul_shiftedLog_global
#check Backlund.eccentricHighRhs_le_kadiriRhs
#check Backlund.log_ne_zero_of_one_lt_re
#check Backlund.shifted_mem_slitPlane_on_verticalClosedStrip
#check Backlund.shifted_log_ne_zero_on_verticalClosedStrip
#check Backlund.shifted_log_mem_slitPlane_on_verticalClosedStrip
#check Backlund.verticalStrip_closure_eq_verticalClosedStrip
#check Backlund.shifted_log_diffContOnCl_on_verticalStrip
#check Backlund.shifted_cpow_const_diffContOnCl_on_verticalStrip
#check Backlund.shifted_log_cpow_const_diffContOnCl_on_verticalStrip
#check Backlund.shiftedLogPowerNormalizer
#check Backlund.norm_shiftedLogPowerNormalizer_ofReal
#check Backlund.shiftedLogPowerNormalizer_ne_zero_on_verticalClosedStrip
#check Backlund.shiftedLogPowerNormalizer_diffContOnCl_on_verticalStrip
#check Backlund.bddAbove_norm_on_verticalClosedStrip_of_phragmen_lindelof
#check Backlund.log_phragmen_lindelof_normalized
#check Backlund.log_phragmen_lindelof_shiftedLogPower
#check Backlund.log_phragmen_lindelof
#check Backlund.rotatedShiftedBase
#check Backlund.rotatedShiftedBase_mem_slitPlane_on_verticalClosedStrip
#check Backlund.rotatedShiftedLogPowerTwoEdgeNormalizer
#check Backlund.rotatedShiftedLogPowerTwoEdgeNormalizer_norm_le_of_upperHalf
#check Backlund.log_phragmen_lindelof_shiftedLogPower_twoEdge
#check Backlund.midpointReflectedProduct
#check Backlund.midpointReflectedProductMajorant
#check Backlund.zetaSurrogate_conj
#check Backlund.midpointReflectedProduct_zetaSurrogate_eq
#check Backlund.reflectedShifted_mem_slitPlane_on_verticalClosedStrip
#check Backlund.reflectedShifted_log_ne_zero_on_verticalClosedStrip
#check Backlund.reflectedShifted_log_mem_slitPlane_on_verticalClosedStrip
#check Backlund.reflectedShifted_log_diffContOnCl_on_verticalStrip
#check Backlund.midpointReflectedProductMajorant_ne_zero_on_verticalClosedStrip
#check Backlund.midpointReflectedProductMajorant_diffContOnCl_on_verticalStrip
#check Backlund.zetaSurrogate_midpointReflectedProduct_PL_inputs
#check Backlund.midpointReflectedProduct_norm_midline
#check Backlund.midpointReflectedProductMajorant_norm_midline
#check Backlund.midpointReflectedProductMajorant_norm_left_boundary
#check Backlund.zetaSurrogate_midpointReflectedProduct_left_boundary_le_one_of_edge_bounds
#check Backlund.midpoint_reflectedProduct_norm_sq_le_majorant_of_verticalStrip
#check Backlund.zetaSurrogate_shiftedLogPower_PL_inputs

#print axioms Backlund.eccentricHighRhs
#print axioms Backlund.kadiriRhs
#print axioms Backlund.zeta_one_line_le_const_mul_log
#print axioms Backlund.backlundA
#print axioms Backlund.backlundA_zero_line_le_const_mul_log
#print axioms Backlund.zetaSurrogate_zero_line_le_const_mul_shiftedLog
#print axioms Backlund.zetaSurrogate_one_line_le_const_mul_shiftedLog
#print axioms Backlund.zetaSurrogate_zero_line_le_const_mul_shiftedLog_global
#print axioms Backlund.zetaSurrogate_one_line_le_const_mul_shiftedLog_global
#print axioms Backlund.eccentricHighRhs_le_kadiriRhs
#print axioms Backlund.log_ne_zero_of_one_lt_re
#print axioms Backlund.shifted_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.shifted_log_ne_zero_on_verticalClosedStrip
#print axioms Backlund.shifted_log_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.verticalStrip_closure_eq_verticalClosedStrip
#print axioms Backlund.shifted_log_diffContOnCl_on_verticalStrip
#print axioms Backlund.shifted_cpow_const_diffContOnCl_on_verticalStrip
#print axioms Backlund.shifted_log_cpow_const_diffContOnCl_on_verticalStrip
#print axioms Backlund.shiftedLogPowerNormalizer
#print axioms Backlund.norm_shiftedLogPowerNormalizer_ofReal
#print axioms Backlund.shiftedLogPowerNormalizer_ne_zero_on_verticalClosedStrip
#print axioms Backlund.shiftedLogPowerNormalizer_diffContOnCl_on_verticalStrip
#print axioms Backlund.bddAbove_norm_on_verticalClosedStrip_of_phragmen_lindelof
#print axioms Backlund.log_phragmen_lindelof_normalized
#print axioms Backlund.log_phragmen_lindelof_shiftedLogPower
#print axioms Backlund.log_phragmen_lindelof
#print axioms Backlund.rotatedShiftedBase
#print axioms Backlund.rotatedShiftedBase_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.rotatedShiftedLogPowerTwoEdgeNormalizer
#print axioms Backlund.rotatedShiftedLogPowerTwoEdgeNormalizer_norm_le_of_upperHalf
#print axioms Backlund.log_phragmen_lindelof_shiftedLogPower_twoEdge
#print axioms Backlund.midpointReflectedProduct
#print axioms Backlund.midpointReflectedProductMajorant
#print axioms Backlund.zetaSurrogate_conj
#print axioms Backlund.midpointReflectedProduct_zetaSurrogate_eq
#print axioms Backlund.reflectedShifted_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.reflectedShifted_log_ne_zero_on_verticalClosedStrip
#print axioms Backlund.reflectedShifted_log_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.reflectedShifted_log_diffContOnCl_on_verticalStrip
#print axioms Backlund.midpointReflectedProductMajorant_ne_zero_on_verticalClosedStrip
#print axioms Backlund.midpointReflectedProductMajorant_diffContOnCl_on_verticalStrip
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_PL_inputs
#print axioms Backlund.midpointReflectedProduct_norm_midline
#print axioms Backlund.midpointReflectedProductMajorant_norm_midline
#print axioms Backlund.midpointReflectedProductMajorant_norm_left_boundary
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_left_boundary_le_one_of_edge_bounds
#print axioms Backlund.midpoint_reflectedProduct_norm_sq_le_majorant_of_verticalStrip
#print axioms Backlund.zetaSurrogate_shiftedLogPower_PL_inputs
