import PrimeNumberTheoremAnd.Backlund.Eccentric

#check Backlund.eccentricHighRhs
#check Backlund.kadiriRhs
#check Backlund.zeta_one_line_le_const_mul_log
#check Backlund.unitNormalize
#check Backlund.coe_unitNormalize
#check Backlund.normalizeNonzeroPath
#check Backlund.PhaseLift
#check Backlund.PhaseLift.change
#check Backlund.PhaseLift.leftEndpointChange
#check Backlund.circlePathOnUnitInterval
#check Backlund.phaseLiftOfCirclePath
#check Backlund.phaseLiftOfCirclePath_exp_phase
#check Backlund.phaseLiftOfNonzeroPath
#check Backlund.phaseLiftOfNonzeroPath_exp_phase
#check Backlund.re_pow_eq_zero_iff_cos_phase_eq_zero
#check Backlund.phaseLiftOfNonzeroPath_re_pow_eq_zero_iff
#check Backlund.firstHitSubtypeSet
#check Backlund.firstHitRealSet
#check Backlund.firstHitPoint
#check Backlund.firstHit
#check Backlund.firstHitPoint_isLeast
#check Backlund.firstHit_mem_Icc
#check Backlund.firstHit_mem
#check Backlund.firstHit_isLeast
#check Backlund.firstHit_eq_of_nonempty
#check Backlund.firstHit_le_of_start_lt_target_of_target_lt_value
#check Backlund.firstHit_le_of_abs_error_at_value
#check Backlund.firstHit_le_firstHit_of_abs_error_at_firstHit
#check Backlund.firstHit_lt_firstHit_of_start_lt_of_target_lt
#check Backlund.firstHit_strictMono_of_strictMono_targets
#check Backlund.firstHit_phaseLift_re_pow_eq_zero
#check Backlund.backlundCosZeroTarget
#check Backlund.backlundCosZeroTarget_cos_eq_zero
#check Backlund.strictMono_backlundCosZeroTarget
#check Backlund.backlundA
#check Backlund.backlundA_conj
#check Backlund.backlundAHorizontalPathFrom
#check Kadiri.zeta_logDeriv_functional_eq
#check Backlund.logDeriv_backlundA_eq_zeta
#check Backlund.logDeriv_backlundA_add_reflected_eq_archimedean
#check Backlund.backlundArchimedeanSymmetryIntegrand
#check Backlund.reflected_half_ne_neg_nat_of_im_ne_zero
#check Backlund.backlundArchimedeanSymmetryIntegrand_eq_shifted_digamma
#check Backlund.arctan_le_self_of_nonneg
#check Backlund.abs_arctan_le_abs_self
#check Backlund.arg_eq_arctan_im_div_re_of_re_pos
#check Backlund.abs_arg_le_abs_im_div_re_of_re_pos
#check Backlund.arg_add_mem_Ioc_of_re_pos
#check Backlund.abs_im_log_add_log_le_mul_im_div_re
#check Backlund.half_reflected_half_product_re
#check Backlund.half_reflected_half_product_im
#check Backlund.abs_half_reflected_half_product_im_div_re_le
#check Backlund.abs_im_log_half_add_log_reflected_half_horizontal_le
#check Backlund.abs_im_digamma_sub_log_sub_half_inv_le
#check Backlund.abs_im_inv_le_inv_abs_im
#check Backlund.abs_im_inv_horizontal_le
#check Backlund.abs_im_inv_half_horizontal_le
#check Backlund.abs_im_inv_reflected_half_horizontal_le
#check Backlund.norm_sq_half_horizontal
#check Backlund.norm_sq_reflected_half_horizontal
#check Backlund.one_div_six_norm_sq_half_horizontal_le_inv
#check Backlund.one_div_six_norm_sq_reflected_half_horizontal_le_inv
#check Backlund.abs_im_inv_pair_average_horizontal_le
#check Backlund.abs_im_digamma_half_add_reflected_half_horizontal_le
#check Backlund.abs_im_backlundArchimedeanSymmetryIntegrand_horizontal_le
#check Backlund.abs_im_HIntegral_le_of_norm_le_const
#check Backlund.abs_im_HIntegral_backlundArchimedeanSymmetryIntegrand_le_of_norm_le_const
#check Backlund.abs_im_HIntegral_le_of_abs_im_le_const_of_le
#check Backlund.abs_im_HIntegral_backlundArchimedeanSymmetryIntegrand_le_of_abs_im_le_const
#check Backlund.abs_im_HIntegral_backlundArchimedeanSymmetryIntegrand_lt_errorBound
#check Backlund.backlund_argument_symmetry_error
#check Backlund.backlundArgumentSymmetryDefect_eq_archimedeanIntegral
#check Backlund.backlundArgumentSymmetryError_of_archimedeanIntegral_bound
#check Backlund.backlundF
#check Backlund.backlundF_real_eq_re
#check Backlund.backlundF_real_eq_zero_iff
#check Backlund.backlundAHorizontalArgumentVariation
#check Backlund.backlundAHorizontalArgumentVariation_self
#check Backlund.backlundAHorizontalArgumentVariation_symm
#check Backlund.backlundArgumentSymmetryDefect
#check Backlund.backlundArgumentSymmetryDefect_self
#check Backlund.backlundArgumentSymmetryErrorBound
#check Backlund.backlundArgumentSymmetryErrorBound_pos
#check Backlund.backlundRealPartZeroSet
#check Backlund.mem_backlundRealPartZeroSet_iff
#check Backlund.mem_backlundRealPartZeroSet_iff_backlundF
#check Backlund.firstHit_backlundAHorizontalPathFrom_mem_realPartZeroSet
#check Backlund.backlundRealPartZeroCount
#check Backlund.backlundRealPartZeroCount_eq_toFinset_card
#check Backlund.backlundOrderedRealPartZeros
#check Backlund.backlundOrderedRealPartZeros_count_le
#check Backlund.backlundCosZeroFirstHits_orderedRealPartZeros
#check Backlund.backlundPairingLoss
#check Backlund.backlundCosZeroTarget_add_gap
#check Backlund.backlundCosZeroTarget_add_le_of_mul_le
#check Backlund.nat_mul_error_lt_pairingLoss_succ_mul_pi
#check Backlund.cosZeroTarget_leftFirstHits_le_rightShiftedFirstHits
#check Backlund.backlundOrderedPairingLowerCount
#check Backlund.backlundOrderedPairingLowerCount_eq_source
#check Backlund.backlundEta
#check Backlund.backlundSmallRadius
#check Backlund.backlundPairingH
#check Backlund.backlundLargeRadius
#check Backlund.backlundPhi₁
#check Backlund.backlundPhi₂
#check Backlund.backlundPhi₃
#check Backlund.backlundEta_pos
#check Backlund.backlundSmallRadius_pos
#check Backlund.backlundPairingH_pos
#check Backlund.backlundLargeRadius_pos
#check Backlund.norm_ofReal_sub_backlundEccentricCenter_eq
#check Backlund.norm_ofReal_sub_backlundEccentricCenter_le_pairingH
#check Backlund.norm_pair_of_backlund_reflected_le_pairingH_sq
#check Backlund.prod_norm_pairs_of_backlund_reflected_le_pairingH_pow
#check Backlund.norm_ofReal_sub_backlundEccentricCenter_le_largeRadius
#check Backlund.backlundEccentricCenter
#check Backlund.backlundEccentricJensenIntegrand
#check Backlund.backlundEccentricJensenIntegral
#check Backlund.backlundEccentricJensenZeroCountRhs
#check Backlund.backlundA_zero_line_le_const_mul_log
#check Backlund.zetaSurrogate_zero_line_le_const_mul_shiftedLog
#check Backlund.zetaSurrogate_one_line_le_const_mul_shiftedLog
#check Backlund.zetaSurrogate_zero_line_le_const_mul_shiftedLog_global
#check Backlund.zetaSurrogate_one_line_le_const_mul_shiftedLog_global
#check Backlund.eccentricHighRhs_le_kadiriRhs
#check Backlund.log_ne_zero_of_one_lt_re
#check Backlund.shifted_mem_slitPlane_on_verticalClosedStrip
#check Backlund.shifted_log_ne_zero_on_verticalClosedStrip
#check Backlund.shifted_log_mem_slitPlane_on_verticalClosedStrip
#check Backlund.verticalStrip_closure_eq_verticalClosedStrip
#check Backlund.shifted_log_diffContOnCl_on_verticalStrip
#check Backlund.shifted_cpow_const_diffContOnCl_on_verticalStrip
#check Backlund.shifted_log_cpow_const_diffContOnCl_on_verticalStrip
#check Backlund.shiftedLogPowerNormalizer
#check Backlund.norm_shiftedLogPowerNormalizer_ofReal
#check Backlund.shiftedLogPowerNormalizer_ne_zero_on_verticalClosedStrip
#check Backlund.shiftedLogPowerNormalizer_diffContOnCl_on_verticalStrip
#check Backlund.bddAbove_norm_on_verticalClosedStrip_of_phragmen_lindelof
#check Backlund.log_phragmen_lindelof_normalized
#check Backlund.log_phragmen_lindelof_shiftedLogPower
#check Backlund.log_phragmen_lindelof
#check Backlund.rotatedShiftedBase
#check Backlund.rotatedShiftedBase_mem_slitPlane_on_verticalClosedStrip
#check Backlund.rotatedShiftedLogPowerTwoEdgeNormalizer
#check Backlund.rotatedShiftedLogPowerTwoEdgeNormalizer_norm_le_of_upperHalf
#check Backlund.log_phragmen_lindelof_shiftedLogPower_twoEdge
#check Backlund.midpointReflectedProduct
#check Backlund.midpointReflectedProductMajorant
#check Backlund.zetaSurrogate_conj
#check Backlund.backlundFEntire
#check Backlund.backlundFEntire_real_eq_re
#check Backlund.backlundFEntire_eq_backlundF_of_shift_ne_one
#check Backlund.backlundEccentricJensenIntegrandEntire
#check Backlund.backlundEccentricJensenIntegralEntire
#check Backlund.backlundEccentricJensenZeroCountRhsEntire
#check Backlund.backlundEccentricJensenIntegralEntire_eq_two_pi_mul_circleAverage
#check Backlund.backlundEccentricTranslatedDivisor
#check Backlund.backlundEccentricTranslatedDivisor_one_le_of_zero
#check Backlund.backlundEccentricTranslatedDivisor_one_le_of_realPartZero
#check Backlund.backlundEccentricTranslatedDivisor_one_le_of_orderedRealPartZeros
#check Backlund.logCounting_lower_bound_of_product
#check Backlund.backlundEccentricJensenLogCountingTerm
#check Backlund.backlundEccentricJensenLogCountingTerm_eq_logCounting_of_center_ne_zero
#check Backlund.backlundEccentricJensenLogCountingTerm_lower_bound_of_orderedRealPartZeros_product
#check Backlund.backlundOrderedRealPartZeros_ne_eccentricCenter
#check Backlund.backlundOrderedRealPartZeros_norm_le_largeRadius
#check Backlund.eccentric_jensen_zero_count_of_orderedRealPartZeros_product_on_backlundInterval
#check Backlund.backlundPairingLoss_le
#check Backlund.eccentric_jensen_zero_count_of_logCounting_lower_bound
#check Backlund.eccentric_jensen_zero_count_of_orderedRealPartZeros_product
#check Backlund.midpointReflectedProduct_zetaSurrogate_eq
#check Backlund.reflectedShifted_mem_slitPlane_on_verticalClosedStrip
#check Backlund.reflectedShifted_log_ne_zero_on_verticalClosedStrip
#check Backlund.reflectedShifted_log_mem_slitPlane_on_verticalClosedStrip
#check Backlund.reflectedShifted_log_diffContOnCl_on_verticalStrip
#check Backlund.midpointReflectedProductMajorant_ne_zero_on_verticalClosedStrip
#check Backlund.midpointReflectedProductMajorant_norm_lower_on_verticalClosedStrip
#check Backlund.zetaSurrogate_midpointReflectedProduct_norm_le_exp_quadratic
#check Backlund.zetaSurrogate_midpointReflectedProduct_quotient_norm_le_exp_quadratic
#check Backlund.zetaSurrogate_midpointReflectedProduct_PL_growth
#check Backlund.midpointReflectedProductMajorant_diffContOnCl_on_verticalStrip
#check Backlund.zetaSurrogate_midpointReflectedProduct_PL_inputs
#check Backlund.midpointReflectedProduct_norm_midline
#check Backlund.midpointReflectedProductMajorant_norm_midline
#check Backlund.midpointReflectedProductMajorant_norm_left_boundary
#check Backlund.midpointReflectedProductMajorant_norm_right_boundary
#check Backlund.zetaSurrogate_midpointReflectedProduct_left_boundary_le_one_of_edge_bounds
#check Backlund.zetaSurrogate_midpointReflectedProduct_left_boundary_le_one_of_re_eq_zero
#check Backlund.zetaSurrogate_midpointReflectedProduct_right_boundary_le_one_of_edge_bounds
#check Backlund.zetaSurrogate_midpointReflectedProduct_right_boundary_le_one_of_re_eq_one
#check Backlund.zetaSurrogate_midpointReflectedProduct_boundary_controls
#check Backlund.midpoint_reflectedProduct_norm_sq_le_majorant_of_verticalStrip
#check Backlund.zetaSurrogate_midpoint_norm_sq_le_majorant
#check Backlund.A_critical_line_quarter_log
#check Backlund.zetaSurrogate_shiftedLogPower_PL_inputs

#print axioms Backlund.eccentricHighRhs
#print axioms Backlund.kadiriRhs
#print axioms Backlund.zeta_one_line_le_const_mul_log
#print axioms Backlund.unitNormalize
#print axioms Backlund.coe_unitNormalize
#print axioms Backlund.normalizeNonzeroPath
#print axioms Backlund.PhaseLift
#print axioms Backlund.PhaseLift.change
#print axioms Backlund.PhaseLift.leftEndpointChange
#print axioms Backlund.circlePathOnUnitInterval
#print axioms Backlund.phaseLiftOfCirclePath
#print axioms Backlund.phaseLiftOfCirclePath_exp_phase
#print axioms Backlund.phaseLiftOfNonzeroPath
#print axioms Backlund.phaseLiftOfNonzeroPath_exp_phase
#print axioms Backlund.re_pow_eq_zero_iff_cos_phase_eq_zero
#print axioms Backlund.phaseLiftOfNonzeroPath_re_pow_eq_zero_iff
#print axioms Backlund.firstHitSubtypeSet
#print axioms Backlund.firstHitRealSet
#print axioms Backlund.firstHitPoint
#print axioms Backlund.firstHit
#print axioms Backlund.firstHitPoint_isLeast
#print axioms Backlund.firstHit_mem_Icc
#print axioms Backlund.firstHit_mem
#print axioms Backlund.firstHit_isLeast
#print axioms Backlund.firstHit_eq_of_nonempty
#print axioms Backlund.firstHit_le_of_start_lt_target_of_target_lt_value
#print axioms Backlund.firstHit_le_of_abs_error_at_value
#print axioms Backlund.firstHit_le_firstHit_of_abs_error_at_firstHit
#print axioms Backlund.firstHit_lt_firstHit_of_start_lt_of_target_lt
#print axioms Backlund.firstHit_strictMono_of_strictMono_targets
#print axioms Backlund.firstHit_phaseLift_re_pow_eq_zero
#print axioms Backlund.backlundCosZeroTarget
#print axioms Backlund.backlundCosZeroTarget_cos_eq_zero
#print axioms Backlund.strictMono_backlundCosZeroTarget
#print axioms Backlund.backlundA
#print axioms Backlund.backlundA_conj
#print axioms Backlund.backlundAHorizontalPathFrom
#print axioms Kadiri.zeta_logDeriv_functional_eq
#print axioms Backlund.logDeriv_backlundA_eq_zeta
#print axioms Backlund.logDeriv_backlundA_add_reflected_eq_archimedean
#print axioms Backlund.backlundArchimedeanSymmetryIntegrand
#print axioms Backlund.reflected_half_ne_neg_nat_of_im_ne_zero
#print axioms Backlund.backlundArchimedeanSymmetryIntegrand_eq_shifted_digamma
#print axioms Backlund.arctan_le_self_of_nonneg
#print axioms Backlund.abs_arctan_le_abs_self
#print axioms Backlund.arg_eq_arctan_im_div_re_of_re_pos
#print axioms Backlund.abs_arg_le_abs_im_div_re_of_re_pos
#print axioms Backlund.arg_add_mem_Ioc_of_re_pos
#print axioms Backlund.abs_im_log_add_log_le_mul_im_div_re
#print axioms Backlund.half_reflected_half_product_re
#print axioms Backlund.half_reflected_half_product_im
#print axioms Backlund.abs_half_reflected_half_product_im_div_re_le
#print axioms Backlund.abs_im_log_half_add_log_reflected_half_horizontal_le
#print axioms Backlund.abs_im_digamma_sub_log_sub_half_inv_le
#print axioms Backlund.abs_im_inv_le_inv_abs_im
#print axioms Backlund.abs_im_inv_horizontal_le
#print axioms Backlund.abs_im_inv_half_horizontal_le
#print axioms Backlund.abs_im_inv_reflected_half_horizontal_le
#print axioms Backlund.norm_sq_half_horizontal
#print axioms Backlund.norm_sq_reflected_half_horizontal
#print axioms Backlund.one_div_six_norm_sq_half_horizontal_le_inv
#print axioms Backlund.one_div_six_norm_sq_reflected_half_horizontal_le_inv
#print axioms Backlund.abs_im_inv_pair_average_horizontal_le
#print axioms Backlund.abs_im_digamma_half_add_reflected_half_horizontal_le
#print axioms Backlund.abs_im_backlundArchimedeanSymmetryIntegrand_horizontal_le
#print axioms Backlund.abs_im_HIntegral_le_of_norm_le_const
#print axioms Backlund.abs_im_HIntegral_backlundArchimedeanSymmetryIntegrand_le_of_norm_le_const
#print axioms Backlund.abs_im_HIntegral_le_of_abs_im_le_const_of_le
#print axioms Backlund.abs_im_HIntegral_backlundArchimedeanSymmetryIntegrand_le_of_abs_im_le_const
#print axioms Backlund.abs_im_HIntegral_backlundArchimedeanSymmetryIntegrand_lt_errorBound
#print axioms Backlund.backlund_argument_symmetry_error
#print axioms Backlund.backlundArgumentSymmetryDefect_eq_archimedeanIntegral
#print axioms Backlund.backlundArgumentSymmetryError_of_archimedeanIntegral_bound
#print axioms Backlund.backlundF
#print axioms Backlund.backlundF_real_eq_re
#print axioms Backlund.backlundF_real_eq_zero_iff
#print axioms Backlund.backlundAHorizontalArgumentVariation
#print axioms Backlund.backlundAHorizontalArgumentVariation_self
#print axioms Backlund.backlundAHorizontalArgumentVariation_symm
#print axioms Backlund.backlundArgumentSymmetryDefect
#print axioms Backlund.backlundArgumentSymmetryDefect_self
#print axioms Backlund.backlundArgumentSymmetryErrorBound
#print axioms Backlund.backlundArgumentSymmetryErrorBound_pos
#print axioms Backlund.backlundRealPartZeroSet
#print axioms Backlund.mem_backlundRealPartZeroSet_iff
#print axioms Backlund.mem_backlundRealPartZeroSet_iff_backlundF
#print axioms Backlund.firstHit_backlundAHorizontalPathFrom_mem_realPartZeroSet
#print axioms Backlund.backlundRealPartZeroCount
#print axioms Backlund.backlundRealPartZeroCount_eq_toFinset_card
#print axioms Backlund.backlundOrderedRealPartZeros
#print axioms Backlund.backlundOrderedRealPartZeros_count_le
#print axioms Backlund.backlundCosZeroFirstHits_orderedRealPartZeros
#print axioms Backlund.backlundPairingLoss
#print axioms Backlund.backlundCosZeroTarget_add_gap
#print axioms Backlund.backlundCosZeroTarget_add_le_of_mul_le
#print axioms Backlund.nat_mul_error_lt_pairingLoss_succ_mul_pi
#print axioms Backlund.cosZeroTarget_leftFirstHits_le_rightShiftedFirstHits
#print axioms Backlund.backlundOrderedPairingLowerCount
#print axioms Backlund.backlundOrderedPairingLowerCount_eq_source
#print axioms Backlund.backlundEta
#print axioms Backlund.backlundSmallRadius
#print axioms Backlund.backlundPairingH
#print axioms Backlund.backlundLargeRadius
#print axioms Backlund.backlundPhi₁
#print axioms Backlund.backlundPhi₂
#print axioms Backlund.backlundPhi₃
#print axioms Backlund.backlundEta_pos
#print axioms Backlund.backlundSmallRadius_pos
#print axioms Backlund.backlundPairingH_pos
#print axioms Backlund.backlundLargeRadius_pos
#print axioms Backlund.norm_ofReal_sub_backlundEccentricCenter_eq
#print axioms Backlund.norm_ofReal_sub_backlundEccentricCenter_le_pairingH
#print axioms Backlund.norm_pair_of_backlund_reflected_le_pairingH_sq
#print axioms Backlund.prod_norm_pairs_of_backlund_reflected_le_pairingH_pow
#print axioms Backlund.norm_ofReal_sub_backlundEccentricCenter_le_largeRadius
#print axioms Backlund.backlundEccentricCenter
#print axioms Backlund.backlundEccentricJensenIntegrand
#print axioms Backlund.backlundEccentricJensenIntegral
#print axioms Backlund.backlundEccentricJensenZeroCountRhs
#print axioms Backlund.backlundA_zero_line_le_const_mul_log
#print axioms Backlund.zetaSurrogate_zero_line_le_const_mul_shiftedLog
#print axioms Backlund.zetaSurrogate_one_line_le_const_mul_shiftedLog
#print axioms Backlund.zetaSurrogate_zero_line_le_const_mul_shiftedLog_global
#print axioms Backlund.zetaSurrogate_one_line_le_const_mul_shiftedLog_global
#print axioms Backlund.eccentricHighRhs_le_kadiriRhs
#print axioms Backlund.log_ne_zero_of_one_lt_re
#print axioms Backlund.shifted_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.shifted_log_ne_zero_on_verticalClosedStrip
#print axioms Backlund.shifted_log_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.verticalStrip_closure_eq_verticalClosedStrip
#print axioms Backlund.shifted_log_diffContOnCl_on_verticalStrip
#print axioms Backlund.shifted_cpow_const_diffContOnCl_on_verticalStrip
#print axioms Backlund.shifted_log_cpow_const_diffContOnCl_on_verticalStrip
#print axioms Backlund.shiftedLogPowerNormalizer
#print axioms Backlund.norm_shiftedLogPowerNormalizer_ofReal
#print axioms Backlund.shiftedLogPowerNormalizer_ne_zero_on_verticalClosedStrip
#print axioms Backlund.shiftedLogPowerNormalizer_diffContOnCl_on_verticalStrip
#print axioms Backlund.bddAbove_norm_on_verticalClosedStrip_of_phragmen_lindelof
#print axioms Backlund.log_phragmen_lindelof_normalized
#print axioms Backlund.log_phragmen_lindelof_shiftedLogPower
#print axioms Backlund.log_phragmen_lindelof
#print axioms Backlund.rotatedShiftedBase
#print axioms Backlund.rotatedShiftedBase_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.rotatedShiftedLogPowerTwoEdgeNormalizer
#print axioms Backlund.rotatedShiftedLogPowerTwoEdgeNormalizer_norm_le_of_upperHalf
#print axioms Backlund.log_phragmen_lindelof_shiftedLogPower_twoEdge
#print axioms Backlund.midpointReflectedProduct
#print axioms Backlund.midpointReflectedProductMajorant
#print axioms Backlund.zetaSurrogate_conj
#print axioms Backlund.backlundFEntire
#print axioms Backlund.backlundFEntire_real_eq_re
#print axioms Backlund.backlundFEntire_eq_backlundF_of_shift_ne_one
#print axioms Backlund.backlundEccentricJensenIntegrandEntire
#print axioms Backlund.backlundEccentricJensenIntegralEntire
#print axioms Backlund.backlundEccentricJensenZeroCountRhsEntire
#print axioms Backlund.backlundEccentricJensenIntegralEntire_eq_two_pi_mul_circleAverage
#print axioms Backlund.backlundFEntire_differentiable
#print axioms Backlund.backlundFEntire_translate_differentiable
#print axioms Backlund.backlundFEntire_translate_jensen_logCounting
#print axioms Backlund.backlundEccentricJensenIntegralEntire_eq_two_pi_mul_logCounting_add_trailingCoeff
#print axioms Backlund.backlundEccentricJensenZeroCountRhsEntire_eq_logCounting_form
#print axioms Backlund.backlundEccentricTranslatedDivisor
#print axioms Backlund.backlundEccentricTranslatedDivisor_one_le_of_zero
#print axioms Backlund.backlundEccentricTranslatedDivisor_one_le_of_realPartZero
#print axioms Backlund.backlundEccentricTranslatedDivisor_one_le_of_orderedRealPartZeros
#print axioms Backlund.logCounting_lower_bound_of_product
#print axioms Backlund.backlundEccentricJensenLogCountingTerm
#print axioms Backlund.backlundEccentricJensenLogCountingTerm_eq_logCounting_of_center_ne_zero
#print axioms Backlund.backlundEccentricJensenLogCountingTerm_lower_bound_of_orderedRealPartZeros_product
#print axioms Backlund.backlundOrderedRealPartZeros_ne_eccentricCenter
#print axioms Backlund.backlundOrderedRealPartZeros_norm_le_largeRadius
#print axioms Backlund.eccentric_jensen_zero_count_of_orderedRealPartZeros_product_on_backlundInterval
#print axioms Backlund.backlundPairingLoss_le
#print axioms Backlund.eccentric_jensen_zero_count_of_logCounting_lower_bound
#print axioms Backlund.eccentric_jensen_zero_count_of_orderedRealPartZeros_product
#print axioms Backlund.midpointReflectedProduct_zetaSurrogate_eq
#print axioms Backlund.reflectedShifted_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.reflectedShifted_log_ne_zero_on_verticalClosedStrip
#print axioms Backlund.reflectedShifted_log_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.reflectedShifted_log_diffContOnCl_on_verticalStrip
#print axioms Backlund.midpointReflectedProductMajorant_ne_zero_on_verticalClosedStrip
#print axioms Backlund.midpointReflectedProductMajorant_norm_lower_on_verticalClosedStrip
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_norm_le_exp_quadratic
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_quotient_norm_le_exp_quadratic
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_PL_growth
#print axioms Backlund.midpointReflectedProductMajorant_diffContOnCl_on_verticalStrip
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_PL_inputs
#print axioms Backlund.midpointReflectedProduct_norm_midline
#print axioms Backlund.midpointReflectedProductMajorant_norm_midline
#print axioms Backlund.midpointReflectedProductMajorant_norm_left_boundary
#print axioms Backlund.midpointReflectedProductMajorant_norm_right_boundary
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_left_boundary_le_one_of_edge_bounds
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_left_boundary_le_one_of_re_eq_zero
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_right_boundary_le_one_of_edge_bounds
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_right_boundary_le_one_of_re_eq_one
#print axioms Backlund.zetaSurrogate_midpointReflectedProduct_boundary_controls
#print axioms Backlund.midpoint_reflectedProduct_norm_sq_le_majorant_of_verticalStrip
#print axioms Backlund.zetaSurrogate_midpoint_norm_sq_le_majorant
#print axioms Backlund.A_critical_line_quarter_log
#print axioms Backlund.zetaSurrogate_shiftedLogPower_PL_inputs
