import PrimeNumberTheoremAnd.Backlund.Eccentric

#check Backlund.eccentricHighRhs
#check Backlund.kadiriRhs
#check Backlund.eccentricHighRhs_le_kadiriRhs
#check Backlund.log_ne_zero_of_one_lt_re
#check Backlund.shifted_mem_slitPlane_on_verticalClosedStrip
#check Backlund.shifted_log_ne_zero_on_verticalClosedStrip
#check Backlund.shifted_log_mem_slitPlane_on_verticalClosedStrip
#check Backlund.verticalStrip_closure_eq_verticalClosedStrip
#check Backlund.shifted_log_diffContOnCl_on_verticalStrip
#check Backlund.shifted_cpow_const_diffContOnCl_on_verticalStrip
#check Backlund.shifted_log_cpow_const_diffContOnCl_on_verticalStrip
#check Backlund.log_phragmen_lindelof_normalized

#print axioms Backlund.eccentricHighRhs
#print axioms Backlund.kadiriRhs
#print axioms Backlund.eccentricHighRhs_le_kadiriRhs
#print axioms Backlund.log_ne_zero_of_one_lt_re
#print axioms Backlund.shifted_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.shifted_log_ne_zero_on_verticalClosedStrip
#print axioms Backlund.shifted_log_mem_slitPlane_on_verticalClosedStrip
#print axioms Backlund.verticalStrip_closure_eq_verticalClosedStrip
#print axioms Backlund.shifted_log_diffContOnCl_on_verticalStrip
#print axioms Backlund.shifted_cpow_const_diffContOnCl_on_verticalStrip
#print axioms Backlund.shifted_log_cpow_const_diffContOnCl_on_verticalStrip
#print axioms Backlund.log_phragmen_lindelof_normalized
